### ISSUE TITLE
Can not call reply inside middleware 

### ISSUE THREAD

**Issue by zamronypj** [mpociot/botman#1226]
- BotMan Version: 2.0
- PHP Version: 7.2
- Messaging Service(s): Web
- Cache Driver: file

### Description:
Calling `$bot->reply()` inside BotMan middleware cause error.

```
[2020-11-17 06:20:06] local.ERROR: Argument 1 passed to BotMan\BotMan\Commands\ConversationManager::addDataParameters() must be an instance of BotMan\BotMan\Messages\Incoming\IncomingMessage, null given, called in /home/zamronypj/works/sindu/nikbot/botnik/vendor/botman/botman/src/BotMan.php on line 493 {"userId":1,"email":"zamronypj@yahoo.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to BotMan\\BotMan\\Commands\\ConversationManager::addDataParameters() must be an instance of BotMan\\BotMan\\Messages\\Incoming\\IncomingMessage, null given, called in /home/zamronypj/works/sindu/nikbot/botnik/vendor/botman/botman/src/BotMan.php on line 493 at /home/zamronypj/works/sindu/nikbot/botnik/vendor/botman/botman/src/Commands/ConversationManager.php:40)
[stacktrace]
#0 /home/zamronypj/works/sindu/nikbot/botnik/vendor/botman/botman/src/BotMan.php(493): BotMan\\BotMan\\Commands\\ConversationManager->addDataParameters(NULL, Array)
#1 /home/zamronypj/works/sindu/nikbot/botnik/vendor/botman/botman/src/BotMan.php(425): BotMan\\BotMan\\BotMan->callMatchingMessages()
#2 /home/zamronypj/works/sindu/nikbot/botnik/app/Http/Controllers/BotManController.php(34): BotMan\\BotMan\\BotMan->listen()
#3 [internal function]: App\\Http\\Controllers\\BotManController->handle()
#4 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#5 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handle', Array)
#6 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\BotManController), 'handle')
#7 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#8 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#9 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#30 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#31 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#32 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#33 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#34 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/zamronypj/works/sindu/nikbot/botnik/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /home/zamronypj/works/sindu/nikbot/botnik/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 /home/zamronypj/works/sindu/nikbot/botnik/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"}
```

### Steps To Reproduce:

Create BotMan middleware which implements `Heard` interface.

```
<?php

namespace App\Http\Controllers;

use BotMan\BotMan\BotMan;
use BotMan\BotMan\Messages\Incoming\IncomingMessage;
use BotMan\BotMan\Interfaces\Middleware\Heard;
use App\User;

class BotmanAuthMiddleware implements Heard
{
    /**
     * Handle a message that was successfully heard, but not processed yet.
     *
     * @param IncomingMessage $message
     * @param callable $next
     * @param BotMan $bot
     *
     * @return mixed
     */
    public function heard(IncomingMessage $message, $next, BotMan $bot)
    {
        $user = $bot->getUser();
        $userId = $user->getId();
        $allowedUser = User::find($user->getId());
        if (! empty($allowedUser)) {
            return $next($message);
        } else {
            return $bot->reply("You are not allowed.");
        }
    }
}
```

**Comment by chimit** [comment]
Try to use `say()` method:

```php
public function heard(IncomingMessage $message, $next, BotMan $bot)
{
    $bot->say('You are not allowed.', $message->getRecipient());

    return $next($message);
}
```

**Comment by zamronypj** [comment]
@chimit  So `$next` must always be called?

**Comment by chimit** [comment]
No, it's just an example. In your case I guess it should be (+ some small refactoring):

```php
<?php

namespace App\Http\Controllers;

use BotMan\BotMan\BotMan;
use BotMan\BotMan\Messages\Incoming\IncomingMessage;
use BotMan\BotMan\Interfaces\Middleware\Heard;
use App\User;

class BotmanAuthMiddleware implements Heard
{
    /**
     * Handle a message that was successfully heard, but not processed yet.
     *
     * @param IncomingMessage $message
     * @param callable $next
     * @param BotMan $bot
     *
     * @return mixed
     */
    public function heard(IncomingMessage $message, $next, BotMan $bot)
    {
        $user = $bot->getUser();
        $userId = $user->getId();
        $allowedUser = User::find($user->getId());

        if (!$allowedUser) {
            return $bot->say('You are not allowed.', $message->getRecipient());
        }

        return $next($message);
    }
}
```

**Comment by zamronypj** [comment]
Calling `$bot->say()` inside middleware throws same exception message.

**Comment by chimit** [comment]
This code is 100% working:

```php
namespace App\Http\Middleware;

use BotMan\BotMan\BotMan;
use BotMan\BotMan\Interfaces\Middleware\Heard;
use BotMan\BotMan\Messages\Incoming\IncomingMessage;

class BotmanHeard implements Heard
{
    public function heard(IncomingMessage $message, $next, BotMan $bot)
    {
        $bot->say('Hello from middleware.', $message->getRecipient());

        return $next($message);
    }
}
```

```php
$middleware = new BotmanHeard();
$botman->middleware->heard($middleware);
```

**Comment by zamronypj** [comment]
@chimit Your code is working because you always call `$next($message)` otherwise it does not work.

**Comment by poplach** [comment]
@chimit The point of middleware is to do some logic 'in between', and `return $next($message);` is a call to a potential next middleware that could be there.

If there are conditions that must give a reply and cancel all the actions - try exiting inside of middleware or throwing/catching exceptions.
