### ISSUE TITLE
local.ERROR: include(): Opis\Closure\ClosureStream::stream_set_option is not implemented!

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [mpociot/botman#1249]
- BotMan Version: 

       "botman/botman": "~2.0",
        "botman/driver-web": "~1.0",
        "botman/studio-addons": "~1.3",
        "botman/tinker": "~1.0",

- PHP Version: PHP 7.4.3
- Messaging Service(s):
- 
- Cache Driver:

### Description:

Error in php 

[2021-01-30 11:58:02] local.ERROR: include(): Opis\Closure\ClosureStream::stream_set_option is not implemented! {"exception":"[object] (ErrorException(code: 0): include(): Opis\\Closure\\ClosureStream::stream_set_option is not implemented! at /var/www/atende.test/vendor/opis/closure/src/SerializableClosure.php:206)
[stacktrace]
#0 /var/www/atende.test/vendor/opis/closure/src/SerializableClosure.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/atende.test/vendor/opis/closure/src/SerializableClosure.php(206): include()
#2 [internal function]: Opis\\Closure\\SerializableClosure->unserialize()

### Steps To Reproduce:

/botman/tinker
Start conversation

**Comment by andersondeoliveiramachado** [comment]
SOLVED !

composer update
