### ISSUE TITLE
The "Symfony\Component\HttpFoundation\Response::create()" method is deprecated

### ISSUE THREAD

**Issue by gymadarasz** [mpociot/botman#1261]
- BotMan Version: ^2.6
- PHP Version: 7.4.3
- Messaging Service(s): Facebook
- Cache Driver: ??

### Steps To Reproduce:
Install Botman standalone following the installation on the page here: `https://botman.io/2.0/installation` and here: `https://botman.io/2.0/driver-facebook-messenger`
Then at the Facebook callback URL verification, the challenge fails with the php error message:
```
[UNKNOWN in /var/www/html/test/vendor/symfony/deprecation-contracts/function.php:25] Since symfony/http-foundation 5.1: The "Symfony\Component\HttpFoundation\Response::create()" method is deprecated, use "new Symfony\Component\HttpFoundation\Response()" instead.
```
A Trace may could helps:
```
#0 [internal function]: error_handler()
#1 /var/www/html/test/vendor/symfony/deprecation-contracts/function.php(25): trigger_error()
#2 /var/www/html/test/vendor/symfony/http-foundation/Response.php(237): trigger_deprecation()
#3 /var/www/html/test/vendor/botman/driver-facebook/src/FacebookDriver.php(120): Symfony\Component\HttpFoundation\Response::create()
#4 /var/www/html/test/vendor/botman/botman/src/Drivers/DriverManager.php(157): BotMan\Drivers\Facebook\FacebookDriver->verifyRequest()
#5 /var/www/html/test/vendor/botman/botman/src/BotMan.php(530): BotMan\BotMan\Drivers\DriverManager::verifyServices()
#6 /var/www/html/test/vendor/botman/botman/src/BotMan.php(416): BotMan\BotMan\BotMan->verifyServices()
#7 /var/www/html/test/cb.php(36): BotMan\BotMan\BotMan->listen()
#8 {main}
```

**Comment by filippotoso** [comment]
This has been fixed in the latest version.
