### ISSUE TITLE
I cannot get run the conversation, cache and parameters of callback are issuing problems

### ISSUE THREAD

**Issue by Yiftach-Yaakov** [mpociot/botman#1262]
- BotMan Version: 2.2
- PHP Version: 7.4
- Messaging Service(s): Slack
- Cache Driver: Doctrine

### Description: I am trying to create a chatbot that only replies on the thread, I am having issues in several times, note that I am using no laravel framework, since the project doesnt allowme such thing. I am 100% php

```
http_response_code(200);
require '/autoload.php';
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
use \BotMan\Drivers\Slack\SlackDriver;
use BotMan\BotMan\Messages\Conversations\Conversation;
use BotMan\BotMan\Cache\DoctrineCache;

//$data=file_get_contents('php://input');
//echo $data->token;

DriverManager::loadDriver(\BotMan\Drivers\Slack\SlackDriver::class);

// Create BotMan instance
$cacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');
$config = [
    'slack' => [
        Xxxxxx
    ],
    'user_cache_time' => 30000,
    'conversation_cache_time' => 30000,
];
// Create an instance
$botman = BotManFactory::create($config, new DoctrineCache($cacheDriver));

// Give the bot something to listen for.
$botman->hears('hello', function (BotMan $bot) {
    $bot->replyInThread('Hello yourself.',[]);
});

$botman->hears('testing', function(BotMan $bot) {
    $bot->startConversation(new OnboardingConversation, "tester", \BotMan\Drivers\Slack\SlackDriver::class);
});

class OnboardingConversation extends Conversation
{
    protected $firstname;

    protected $email;

    public function ask($question, $next, $additionalParameters = [])
    {
        $this->bot->replyInThread($question, $additionalParameters);
        $this->bot->storeConversation($this, $next, $question, $additionalParameters);

        return $this;
    }

    public function say($message, $additionalParameters = [])
    {
        $this->bot->replyInThread($message, $additionalParameters);

        return $this;
    }

    public function askFirstname()
    {
        $this->ask('Hello! What is your firstname?', function(Answer $answer, $conversation=null) {
            // Save result
            $this->firstname = $answer->getText();

            $this->say('Nice to meet you '.$this->firstname);
            $this->askEmail();
        });
    }

    public function askEmail()
    {
        $this->ask('One more thing - what is your email?', function(Answer $answer, $conversation=null) {
            // Save result
            $this->email = $answer->getText();

            $this->say('Great - that is all we need, '.$this->firstname);
        });
    }

    public function run()
    {
        // This will be called immediately
        $this->askFirstname();
    }
}

// Start listening
$botman->listen();//file_get_contents('php://input'));
```

### Exceptions: I am getting two exceptions depending if i delete de cache folder, and i get rid of the whole conversation class.

this is the first and is weird since actually it is working whith the simple hear command out of the conversation, besides the sequence of the creation of the conversation I think is correct.

```
[24-Mar-2021 01:56:40 America/Mexico_City] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /vendor/botman/driver-slack/src/SlackDriver.php:273
Stack trace:
#0 /vendor/botman/botman/src/BotMan.php(747): BotMan\Drivers\Slack\SlackDriver->replyInThread('Hello! What is ...', Array, Object(BotMan\BotMan\Messages\Incoming\IncomingMessage), Object(BotMan\BotMan\BotMan))
#1 /public_html/genius/botman.php(46): BotMan\BotMan\BotMan->__call('replyInThread', Array)
#2 /public_html/genius/botman.php(67): OnboardingConversation->ask('Hello! What is ...', Object(Closure))
#3 /public_html/genius/botman.php(83): OnboardingConversation->askFirstname()
#4 /vendor/botman/botman/src/Traits/HandlesConversations.php(28): OnboardingConversation->run()
#5 /public_html/genius/botman.php(35): BotMan\BotMan\BotMan->startConversation(Object(OnboardingConversation), 'tester', 'BotMan\\Drivers\\...')
#6 [internal function]: {closure}(Object(BotMan\BotMan\BotMan in /home1/einfinito/vendor/botman/driver-slack/src/SlackDriver.php on line 273
```

The second one, which I simply just doesnt understand is this: 

```
[24-Mar-2021 01:53:13 America/Mexico_City] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to OnboardingConversation::{closure}() must be an instance of Answer, instance of BotMan\BotMan\Messages\Incoming\Answer given in closure://function(\Answer $answer) {
            // Save result
            $this->firstname = $answer->getText();

            $this->say('Nice to meet you '.$this->firstname);
            $this->askEmail();
        }:2
Stack trace:
#0 [internal function]: OnboardingConversation->{closure}(Object(BotMan\BotMan\Messages\Incoming\Answer), Object(OnboardingConversation))
#1 /vendor/botman/botman/src/Traits/HandlesConversations.php(306): call_user_func_array(Object(Closure), Array)
#2 /vendor/botman/botman/src/Traits/HandlesConversations.php(284): BotMan\BotMan\BotMan->prepareConversationClosure(Object(Closure), Object(OnboardingConversation), Array)
#3 /vendor/botman/botman/src/Traits/HandlesConversations.php(241): BotMan\BotMan\BotMan->callConversation(Object(Opis\Closure\SerializableClosure in closure://function(\Answer $answer) {
            // Save result
            $this->firstname = $answer->getText();

            $this->say('Nice to meet you '.$this->firstname);
            $this->askEmail();
        } on line 2
```

Actually i added the `$conversation =  null` because of the prepareConversationClosure method, but I am not getting fix it yet.

I don't know if someone could iluminate me

Thanks so much

**Comment by Yiftach-Yaakov** [comment]
I solved, it is weird but i think it solved by itself, eben though i did a pletory of tests.

I see a lot potential in this
