### ISSUE TITLE
Can't catch "File is too big" error

### ISSUE THREAD

**Issue by Neolot** [mpociot/botman#1273]
- BotMan Version: 2.6.1
- PHP Version: 7.4.21
- Messaging Service(s): Telegram
- Cache Driver: TelegramDriver

### Description:

I want to catch the error "File is too big" to inform user about it, but the exception is not caught, only an error is sent to the log.

### Steps To Reproduce:

Here is my `botman.php` excerpt:
```php
<?php
use App\Http\Controllers\BotManController;
use BotMan\BotMan\BotMan;
use BotMan\Drivers\Telegram\Exceptions\TelegramAttachmentException;

$botman = resolve('botman');

// Video
try {
    $botman->receivesVideos(function($bot, $video) {
        $bot->startConversation(new Tasks\VideoTaskConversation());
    });
} catch ( TelegramAttachmentException $e ) {
    Log::debug('Attachment too big');
}
```

Log:
```
[2021-07-09 09:53:09] local.ERROR: Error retrieving file url: Bad Request: file is too big {"exception":"[object] (BotMan\\Drivers\\Telegram\\Exceptions\\TelegramAttachmentException(code: 0): Error retrieving file url: Bad Request: file is too big at /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/botman/driver-telegram/src/TelegramVideoDriver.php:76)
[stacktrace]
#0 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/botman/driver-telegram/src/TelegramVideoDriver.php(56): BotMan\\Drivers\\Telegram\\TelegramVideoDriver->getVideos()
#1 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/botman/driver-telegram/src/TelegramVideoDriver.php(39): BotMan\\Drivers\\Telegram\\TelegramVideoDriver->loadMessages()
#2 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/botman/botman/src/BotMan.php(192): BotMan\\Drivers\\Telegram\\TelegramVideoDriver->getMessages()
#3 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/botman/botman/src/Traits/HandlesConversations.php(170): BotMan\\BotMan\\BotMan->getMessages()
#4 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/botman/botman/src/BotMan.php(422): BotMan\\BotMan\\BotMan->loadActiveConversation()
#5 /home/neolot/Projects/LTS/taskbot_pro_botman/app/Http/Controllers/BotManController.php(25): BotMan\\BotMan\\BotMan->listen()
#6 [internal function]: App\\Http\\Controllers\\BotManController->handle()
#7 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#8 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#9 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#11 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#12 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#14 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#15 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#17 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#18 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#20 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#21 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#23 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#26 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#27 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#29 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#30 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#32 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then()
#33 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack()
#34 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute()
#35 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute()
#36 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#37 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#38 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#39 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle()
#40 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#42 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#43 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#45 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#48 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#49 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#51 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#52 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#54 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#55 /home/neolot/Projects/LTS/taskbot_pro_botman/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /home/neolot/Projects/LTS/taskbot_pro_botman/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 /home/neolot/Projects/LTS/taskbot_pro_botman/server.php(21): require_once('/home/neolot/Pr...')
#58 {main}
"} 
```
As you can see, my debug message is not there, only an error message.

How to catch "File is too big" error?

**Comment by IljaPHP** [comment]
I find just the one way to catch it. In the initialisation file, by the listen method.
```
      try {
         $this->myBot->listen();
      } catch (TelegramAttachmentException $e) {
         Yii::error('catched ' . $e->getMessage());
      }
```
But I can't write to user about mistake from this program level. Can't get the user id from  $this->myBot to use say method. Have someone any idea about it?

**Comment by filippotoso** [comment]
Solved in version 2 of Telegram Driver.

See details here: https://github.com/botman/driver-telegram/issues/53
