### ISSUE TITLE
SlackRTMDriver ATTACHMENT_PATTERN doesn't exist

### ISSUE THREAD

**Issue by drakenya** [mpociot/botman#323]
- BotMan Version: 1.5.2
- PHP Version: 7.1.3
- Messaging Service(s): SlackRTM
- Cache Driver: none

### Description:
There is an uncaught exception when botman listens on a slack channel and a post is attached to a channel.

It seems to have been added in #305, two instances of BotMan::ATTACHMENT_PATTERN were added but no class constant was actually defined.

The exception, less the directories:
```

Fatal error: Uncaught Error: Undefined class constant 'ATTACHMENT_PATTERN' in /.../vendor/mpociot/botman/src/Mpociot/BotMan/Drivers/SlackRTMDriver.php:108
Stack trace:
#0 /.../vendor/mpociot/botman/src/Mpociot/BotMan/BotMan.php(168): Mpociot\BotMan\Drivers\SlackRTMDriver->getMessages()
#1 /.../vendor/mpociot/botman/src/Mpociot/BotMan/Traits/HandlesConversations.php(138): Mpociot\BotMan\BotMan->getMessages()
#2 /.../vendor/mpociot/botman/src/Mpociot/BotMan/BotMan.php(330): Mpociot\BotMan\BotMan->loadActiveConversation()
#3 /.../vendor/mpociot/botman/src/Mpociot/BotMan/BotManFactory.php(87): Mpociot\BotMan\BotMan->listen()
#4 [internal function]: Mpociot\BotMan\BotManFactory::Mpociot\BotMan\{closure}(Object(Slack\Payload))
#5 /.../vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Object(Closure), Array)
#6 /.../vendor/coderstephen/slack-client/src/RealTim in /Users/akrol01/code/bot/vendor/mpociot/botman/src/Mpociot/BotMan/Drivers/SlackRTMDriver.php on line 108

```

### Steps To Reproduce:

Start a slack RTM bot
Create a simple listener
```php
<?php
use Mpociot\BotMan\BotMan;

$loop = Factory::create();

$config = [
    'slack_token' => '...',
];

$botman = BotManFactory::createForRTM($config, $loop);

$botman->hears('(.+)', function (BotMan $bot, $message) use ($parser) {
    $bot->reply('oops');
});

$loop->run();
```
Invite to a Slack channel

Attach a post to the slack channel (green + next to the message bar, pick Post and fill it out).

**Comment by mpociot** [comment]
Fixed in 1.5.3
