### ISSUE TITLE
BotmanCache handle error

### ISSUE THREAD

**Issue by feralheart** [mpociot/botman#880]
- BotMan Version: 2
- PHP Version: 7.2
- Messaging Service(s): Core
- Cache Driver: file

### Description:
When I wanted to set `php artisan down` I got this error:

```
PHP Warning:  Uncaught ErrorException: Declaration of BotMan\Studio\Console\Commands\BotManCacheClear::handle(Illuminate\Filesystem\Filesystem $files) should be compatible with Illuminate\Console\GeneratorCommand::handle() in /var/www/botond/vendor/botman/studio-addons/src/Console/Commands/BotManCacheClear.php:50
Stack trace:
#0 /var/www/botond/vendor/composer/ClassLoader.php(412): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Declaration of ...', '/var/www/botond...', 50, Array)
#1 /var/www/botond/vendor/composer/ClassLoader.php(412): include()
#2 /var/www/botond/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/botond...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('BotMan\\Studio\\C...')
#4 [internal function]: spl_autoload_call('BotMan\\Studio\\C...')
#5 /var/www/botond/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('BotMan\\Studio\\C...')
#6 /var/www/botond/vendor/laravel/framework/src/Illuminate/C in /var/www/botond/vendor/botman/studio-addons/src/Console/Commands/BotManCacheClear.php on line 50
PHP Fatal error:  Class BotMan\Studio\Console\Commands\BotManCacheClear contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Illuminate\Console\GeneratorCommand::getStub) in /var/www/botond/vendor/botman/studio-addons/src/Console/Commands/BotManCacheClear.php on line 50
```

### Steps To Reproduce:

**Comment by rapliandras** [comment]
#metoo but. You should never rewrite the contents of `vendor` folder. Wait for an official bugfix or use inheritance / override botman:cache:clear with another class in config.
